{"name": "adding with valid details", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'verify_account_added'\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\add_bankaccount.py\", line 45, in step_impl\n    assert context.verify_account_added(\"Account added\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "steps": [{"name": "Given I logged in and got navigated to Home page", "status": "passed", "start": 1693301147496, "stop": 1693301153573}, {"name": "When I click on my account and go to payment options and click on manage bank accounts", "status": "passed", "start": 1693301153573, "stop": 1693301199920}, {"name": "And I enter all the valid details", "status": "passed", "start": 1693301199920, "stop": 1693301226954}, {"name": "Then account added message should be displayed", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'verify_account_added'\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\add_bankaccount.py\", line 45, in step_impl\n    assert context.verify_account_added(\"Account added\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "attachments": [{"name": "screenshot", "source": "d6474d7c-eca8-4556-acfb-fc13760f06ce-attachment.png", "type": "image/png"}], "start": 1693301226954, "stop": 1693301227258}], "start": 1693301139685, "stop": 1693301235020, "uuid": "33035608-6390-4747-aab0-27eb6c253a9e", "historyId": "b34baa758e5039879f5c386138c57b80", "fullName": "add new bank account: adding with valid details", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "bank"}, {"name": "feature", "value": "add new bank account"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}