{"name": "adding with valid details", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'verify_account_added'\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\add_bankaccount.py\", line 46, in step_impl\n    assert context.verify_account_added(\"Account added\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "steps": [{"name": "Given I logged in and got navigated to Home page", "status": "passed", "start": 1693474311617, "stop": 1693474345237}, {"name": "When I click on my account and go to payment options and click on manage bank accounts", "status": "passed", "start": 1693474345238, "stop": 1693474377266}, {"name": "And I enter all the valid details", "status": "passed", "start": 1693474377266, "stop": 1693474402058}, {"name": "Then account added message should be displayed", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'verify_account_added'\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\add_bankaccount.py\", line 46, in step_impl\n    assert context.verify_account_added(\"Account added\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "attachments": [{"name": "screenshot", "source": "7f49d7cd-c9ab-4081-bed8-b4df99d323b9-attachment.png", "type": "image/png"}], "start": 1693474402059, "stop": 1693474402200}], "start": 1693474297321, "stop": 1693474409959, "uuid": "e5b76396-18a1-4bac-9f14-b6ced3db920e", "historyId": "b34baa758e5039879f5c386138c57b80", "fullName": "add new bank account: adding with valid details", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "bank"}, {"name": "feature", "value": "add new bank account"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}